<?php
Route::get('/', 'PublicController@index');
Route::get('/Todos/Listado', 'PublicController@Todos');
Route::get('/Sitios/Listado', 'PublicController@Sitios');
Route::get('/Campos/Listado', 'PublicController@Campos');
Route::get('/Parcelas/Listado', 'PublicController@Parcelas');
Route::get('/Plantaciones/Listado', 'PublicController@Plantaciones');
Route::get('/Industriales/Listado', 'PublicController@Industriales');
Route::get('/Lotes/Listado', 'PublicController@Lotes');
Route::get('/Casas/Listado', 'PublicController@Casas');
Route::get('/Terreno/{id}', 'PublicController@Terreno');
Route::get('/Casa/{id}', 'PublicController@Casa');
Route::get('/Casas', 'PublicController@Redirecciones');
Route::get('/Parcelas', 'PublicController@Redirecciones');
Route::get('/Campos', 'PublicController@Redirecciones');
Route::get('/Industriales', 'PublicController@Redirecciones');
Route::get('/Plantaciones', 'PublicController@Redirecciones');
Route::get('/Lotes', 'PublicController@Redirecciones');
Route::group(['middleware' => 'admin'], function () {
    Route::get('/ControlAdmin', 'AdminController@index');
    Route::get('/ControlAdmin/Terreno', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Casa', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Casa/Editar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Terreno/Editar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Terreno/EditarRegiones', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Region', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Region/Editar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Region/Eliminar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Casa/Provincia', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Editar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Eliminar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Comuna', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Comuna/Editar', 'AdminController@Redirecciones');
    Route::get('/ControlAdmin/Comuna/Eliminar', 'AdminController@Redirecciones');
    Route::resource('/Terreno','TerrenoController');
    Route::resource('/Casa','CasaController');
    Route::resource('/Comuna','ComunaController');
    Route::resource('/Provincia','ProvinciaController');
    Route::resource('/Region','RegionController');
    Route::get('/ControlAdmin/RegionContador', 'RegionController@RegionContador');
    Route::get('/ControlAdmin/ProvinciasContador', 'ProvinciaController@ProvinciasContador');
    Route::get('/ControlAdmin/ComunasContador', 'ComunaController@ComunaContador');
    Route::get('/ControlAdmin/TerrenoContador', 'TerrenoController@TerrenoContador');
    Route::get('/ControlAdmin/TerrenoSitios', 'TerrenoController@TerrenoSitios');
    Route::get('/ControlAdmin/TerrenoParcelas', 'TerrenoController@TerrenoParcelas');
    Route::get('/ControlAdmin/TerrenoCampos', 'TerrenoController@TerrenoCampos');
    Route::get('/ControlAdmin/TerrenoPlantaciones', 'TerrenoController@TerrenoPlantaciones');
    Route::get('/ControlAdmin/TerrenoIndustriales', 'TerrenoController@TerrenoIndustriales');
    Route::get('/ControlAdmin/TerrenoVContador', 'TerrenoController@TerrenoVContador');
    Route::get('/ControlAdmin/TerrenoDContador', 'TerrenoController@TerrenoDContador');
    Route::get('/ControlAdmin/CasaContador', 'CasaController@CasaContador');
    Route::get('/ControlAdmin/CasaDContador', 'CasaController@CasaDContador');
    Route::get('/ControlAdmin/CasaVContador', 'CasaController@CasaVContador');
    Route::put('/ControlAdmin/TerrenoVendido/{id}','TerrenoController@Vendido');
    Route::put('/ControlAdmin/CasaVendido/{id}','CasaController@Vendido');
    Route::put('/ControlAdmin/TerreninUpdateImg/{id}','TerrenoController@updateImagen');
    Route::put('/ControlAdmin/TerrenoUpdateRegion/{id}','TerrenoController@updateRegion');
    Route::put('/ControlAdmin/CasaUpdateRegion/{id}','CasaController@updateRegion');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
